# GNU General Public License v3.0+ (see LICENSES/GPL-3.0-or-later.txt or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later
# SPDX-FileCopyrightText: 2025 Felix Fontein <felix@fontein.de>

line-length = 120
target-version = "py37"

[lint]
# https://docs.astral.sh/ruff/rules/

select = ["A", "B", "D", "E", "F", "FA", "FLY", "UP", "SIM", "I", "RUF022", "PL"]
ignore = [
    # Better keep ignored (for now)
    "F811",  # Redefinition of unused `xxx` (happens a lot for fixtures in unit tests)
    "E402",  # Module level import not at top of file
    "E741",  # Ambiguous variable name
    "UP012",  # unnecessary-encode-utf8
    "UP015",  # Unnecessary mode argument
    "SIM105",  # suppressible-exception
    "SIM108",  # if-else-block-instead-of-if-exp
    "D100", # Missing docstring in public module
    "D107", # undocumented-public-init
    "D203", # incorrect-blank-line-before-class, mutually exclusive to D211
    "D212", # multi-line-summary-first-line, mutually exclusive to D213
]

# Allow fix for all enabled rules (when `--fix`) is provided.
fixable = ["ALL"]
unfixable = []

# Allow unused variables when underscore-prefixed or starting with dummy
dummy-variable-rgx = "^(_|dummy).*$"


[lint.per-file-ignores]
# Only require docstrings for shared utils
"!**/*_utils/*.py" = ["D"]
"**/plugins/connection/proxmox_pct_remote.py" = ["B007", "B904", "PLR0912", "PLR0915", "PLW1508", "UP006"]
"**/plugins/inventory/proxmox.py" = ["B904", "PLC0415", "PLR0912", "PLW2901", "SIM102", "SIM201", "SIM401"]
"**/plugins/module_utils/_filelock.py" = ["D200", "D205", "D415", "PLR2004", "SIM115", "UP036"]
"**/plugins/module_utils/proxmox_sdn.py" = ["D102", "D415", "FA100", "PLR2004"]
"**/plugins/modules/proxmox.py" = ["B904", "PLR0912", "PLR0913"]
"**/plugins/modules/proxmox_backup.py" = ["PLR0912", "PLR0913", "SIM102"]
"**/plugins/modules/proxmox_cluster_ha_groups.py" = ["PLR0913"]
"**/plugins/modules/proxmox_cluster_ha_resources.py" = ["PLR0913"]
"**/plugins/modules/proxmox_disk.py" = ["A004", "PLR0912", "PLR0915", "PLR2004"]
"**/plugins/modules/proxmox_firewall.py" = ["PLR0912"]
"**/plugins/modules/proxmox_kvm.py" = ["F841", "PLR0912", "PLR0913", "PLR0915", "PLR2004", "PLW0603", "SIM102", "SIM103", "SIM118"]
"**/plugins/modules/proxmox_nic.py" = ["PLR0912"]
"**/plugins/modules/proxmox_node.py" = ["PLR0912", "PLR0915", "SIM102"]
"**/plugins/modules/proxmox_node_network.py" = ["PLR0912", "PLR2004", "PLW2901", "SIM102"]
"**/plugins/modules/proxmox_snap.py" = ["PLR0912", "PLR0913", "PLR0915"]
"**/plugins/modules/proxmox_storage.py" = ["PLR0912", "PLR0915"]
"**/plugins/modules/proxmox_subnet.py" = ["F841", "PLR0912", "PLR0915", "SIM102"]
"**/plugins/modules/proxmox_template.py" = ["PLR0912", "PLR0913", "PLR0915", "PLR2004", "SIM102", "SIM115"]
"**/plugins/modules/proxmox_user.py" = ["PLR0913"]
"**/plugins/modules/proxmox_vm_info.py" = ["A001", "A002", "PLR0913"]
"**/plugins/modules/proxmox_vnet.py" = ["PLR0912"]
"**/plugins/plugin_utils/unsafe.py" = ["D103", "PLR0911"]
"**/tests/unit/plugins/connection/test_proxmox_pct_remote.py" = ["PLR0913", "PLR2004"]
"**/tests/unit/plugins/inventory/test_proxmox.py" = ["PLR0911", "PLR0912", "SIM116"]
"**/tests/unit/plugins/modules/test_proxmox_backup.py" = ["PLR2004"]
"**/tests/unit/plugins/modules/test_proxmox_backup_info.py" = ["PLR2004", "SIM117"]
"**/tests/unit/plugins/modules/test_proxmox_cluster_ha_rules.py" = ["PLR2004"]
"**/tests/unit/plugins/modules/test_proxmox_node_network.py" = ["A006"]
"**/tests/unit/plugins/modules/test_proxmox_node_network_info.py" = ["A006"]
"**/tests/unit/plugins/modules/test_proxmox_sendkey.py" = ["F841", "PLR2004"]
"**/tests/unit/plugins/modules/test_proxmox_snap.py" = ["A002", "F841"]
"**/tests/unit/plugins/modules/test_proxmox_snap_info.py" = ["A002", "PLR2004"]
"**/tests/unit/plugins/modules/test_proxmox_storage_contents_info.py" = ["F841"]
"**/tests/unit/plugins/modules/test_proxmox_subnet.py" = ["PLR0913"]
"**/tests/unit/plugins/modules/test_proxmox_vm_info.py" = ["A002"]

[lint.pydocstyle]
# force users to include their variables in docstrings to improve editor support
ignore-var-parameters = false
# quite similar to the yaml we already use as ansible documentation
convention = "google"


[lint.isort]
# The resulting order is: stdlib, third-party, e.g. ansible, first-party, e.g. ansible_collections.community.proxmox.*, local
known-first-party = [
    "ansible_collections.community.proxmox",
]
known-third-party = [
    "ansible_collections.community.internal_test_tools",
]

[lint.pycodestyle]
max-line-length = 160

[format]
# https://docs.astral.sh/ruff/formatter/#configuration
# Like Black, use double quotes for strings.
quote-style = "double"

# Like Black, indent with spaces, rather than tabs.
indent-style = "space"

# Like Black, respect magic trailing commas.
skip-magic-trailing-comma = false

line-ending = "lf"

# Disable auto-formatting of code examples in docstrings. Markdown,
# reStructuredText code/literal blocks and doctests are all supported.
docstring-code-format = false


